name: Deploy

on:
  push:
    branches:
      - feature/LOC-72

jobs:
  deploy:
    runs-on: database
    steps:
      - name: Remove Docker container
        run: docker rm -f ${{ secrets.DOCKER_CONTAINER_DATABASE }}

      - name: Remove unused Docker images
        run: docker image prune -a -f

      - name: Run Docker container
        run: docker run -d --name ${{ secrets.DOCKER_CONTAINER_DATABASE }} --network ${{ secrets.DOCKER_NETWORK }} --mount "${{ secrets.DOCKER_VOLUME_DATABASE_PATH }}"  -v /home/ubuntu/my.cnf:/etc/mysql/my.cnf -e MYSQL_ROOT_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }} -e MYSQL_DATABASE=${{ secrets.DATABASE_SCHEMA }} -e MYSQL_USER=${{ secrets.DATABASE_USER_NAME }} -e MYSQL_PASSWORD='${{ secrets.DATABASE_USER_PASSWORD }}' -p 3306:3306 mysql:latest 
        
  configure-database:
    needs: deploy
    runs-on: database
    steps:
      - name: Flush the privileges for the user
        run: |
          docker exec -i ${{ secrets.DOCKER_CONTAINER_DATABASE }} mysql -u root -p${{ secrets.DATABASE_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ secrets.DATABASE_SCHEMA }}.* TO '${{ secrets.DATABASE_USER_NAME }}'@'%';"
          docker exec -i ${{ secrets.DOCKER_CONTAINER_DATABASE }} mysql -u root -p${{ secrets.DATABASE_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"
